# .github/workflows/main.yml

# Workflow name
name: 'UI Tests'

# Event for the workflow
on:
  pull_request:
      branches:
        - main

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        # 👇 Install dependencies with the same package manager used in the project (replace it as needed), e.g. yarn, npm, pnpm
        run: yarn
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        id: chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
  
  print-results:
    runs-on: ubuntu-latest
    needs: chromatic-deployment
    steps:
      - name: Publish Summary
        run: echo -e "| Results |  |\n| --- | --- |\n| Build Results | ${{steps.chromatic.outputs.buildUrl}} |\n| Storybook Preview | ${{steps.chromatic.outputs.storybookUrl}} |\n| Component Count | ${{steps.chromatic.outputs.componentCount}} |" >> $GITHUB_STEP_SUMMARY

  publish-job-summary:
    runs-on: ubuntu-latest
    name: Publish URLs
    needs: chromatic-deployment
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2.4.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message:
            summary ${{GITHUB_STEP_SUMMARY}}
