# .github/workflows/main.yml

# Workflow name
name: 'Chromatic'

# Event for the workflow
on:
  pull_request:
      branches:
        - main

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        # 👇 Install dependencies with the same package manager used in the project (replace it as needed), e.g. yarn, npm, pnpm
        run: yarn
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
  Build-summary-on-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      id: test
    - uses: LouisBrunner/checks-action@v1.6.2
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Test Summary
        conclusion: success
        output: |
          {"summary":"${{ steps.test.outputs.summary }}"}